### PR TITLE
Filters, search bar, navigation using category from home page, loaders, and alert messages

### PR DESCRIPTION
**Pull request by xsaurabhsuthar**
* Loader
image
* Alert added for login updates.
image
* Search Bar
image
image

### CODE REVIEW

**Comment by Launchpad5682** [comment]
Preview @ https://calm-stream-93dzvzaya-launchpad5682.vercel.app/

**Review by SK02K1 — APPROVED** [review]
- Everything is looking good 

   @Launchpad5682 great work 🙌🏻

**Review by Ash-D23 — APPROVED** [review]
Good structure, clean code
Suggest you to avoid so many files in a pr

**Comment by xsaurabhsuthar** [comment]
Sorry for that @Ash-D23 . Will not repeat in future. Thanks for the review @Ash-D23  @SK02K1

**Pull request merged**
